name: VanillaElytra
softdepend: Firework
main: JavierLeon9966\VanillaElytra\VanillaElytra
author: JavierLeon9966
version: 1.14.0
api: 5.0.0
mcpe-protocol: [431, 440, 448, 465, 471, 475, 486, 503, 527, 534, 544, 545, 554, 557, 560, 567, 575, 582, 589, 594, 618]
description: A plugin that implements vanilla Elytra into PocketMine-MP
